export const sitesDataArrObj = [
  {
    img: "/techscriptorium.png",
    hosted: "vercel",
    siteName: "TechScriptorium",
    url: "https://techscriptorium.vercel.app/",
    github: "lexuscreations",
  },
  {
    img: "/lexus-mausamapp.png",
    hosted: "netlify",
    siteName: "MausamApp",
    url: "https://lexus-mausamapp.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/lexus-top-github.png",
    hosted: "netlify",
    siteName: "LexusTopGithub",
    url: "https://lexus-top-github.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/lexusdevresources.png",
    hosted: "netlify",
    siteName: "LexusDevResources",
    url: "https://lexusdevresources.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/image-to-base64-base64-to-image.png",
    hosted: "netlify",
    siteName: "ImgToB64-B64ToImg",
    url: "https://image-to-base64-base64-to-image.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/lexuscumin.png",
    hosted: "netlify",
    siteName: "LexusCumin",
    url: "https://lexuscumin.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/shopieezon.png",
    hosted: "netlify",
    siteName: "Shopieezon",
    url: "https://shopieezon.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/lexuspostman.png",
    hosted: "netlify",
    siteName: "LexusPostman",
    url: "https://lexuspostman.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/codeconnect.png",
    hosted: "render",
    siteName: "CodeConnect",
    url: "https://codeconnect.onrender.com/",
    github: "lexuscreations",
  },
  {
    img: "/lexuscreations.png",
    hosted: "netlify",
    siteName: "LexusCreations",
    url: "https://lexuscreations.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/lexusprint.png",
    hosted: "githubPages",
    siteName: "LexusPrint",
    url: "https://lexuscreations.github.io/lexusprint/",
    github: "lexuscreations",
  },
  {
    img: "/independentwomencommunity.png",
    hosted: "netlify",
    siteName: "IndependentWomenCommunity",
    url: "https://independentwomencommunity.netlify.app/",
    github: "lexuscreations",
  },
  {
    img: "/worklokeshvishwakarma.png",
    hosted: "githubPages",
    siteName: "TextCapital",
    url: "https://worklokeshvishwakarma.github.io/textcapital/",
    github: "worklokeshvishwakarma",
  },
  {
    img: "/leapyearfinder.png",
    hosted: "githubPages",
    siteName: "LeapYearFinder",
    url: "https://worklokeshvishwakarma.github.io/leapyearfinder/",
    github: "worklokeshvishwakarma",
  },
  {
    img: "/d2b-b2d-converter.png",
    hosted: "githubPages",
    siteName: "DarkSite",
    url: "https://lexuscreations.github.io/darksite/",
    github: "lexuscreations",
  },
  {
    img: "/darksite.png",
    hosted: "githubPages",
    siteName: "D2B-B2D-Converter",
    url: "https://worklokeshvishwakarma.github.io/d2b-b2d-converter/",
    github: "worklokeshvishwakarma",
  },
];
