export const sitesDataArrObj = [
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-01.jpg",
    hosted: "vercel",
    siteName: "TechScriptorium",
    url: "https://techscriptorium.vercel.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-02.jpg",
    hosted: "netlify",
    siteName: "MausamApp",
    url: "https://lexus-mausamapp.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-03.jpg",
    hosted: "netlify",
    siteName: "LexusTopGithub",
    url: "https://lexus-top-github.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-04.jpg",
    hosted: "netlify",
    siteName: "LexusDevResources",
    url: "https://lexusdevresources.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-01.jpg",
    hosted: "netlify",
    siteName: "ImgToB64-B64ToImg",
    url: "https://image-to-base64-base64-to-image.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-02.jpg",
    hosted: "netlify",
    siteName: "LexusCumin",
    url: "https://lexuscumin.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-03.jpg",
    hosted: "netlify",
    siteName: "Shopieezon",
    url: "https://shopieezon.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-04.jpg",
    hosted: "netlify",
    siteName: "LexusPostman",
    url: "https://lexuspostman.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-01.jpg",
    hosted: "heroku",
    siteName: "LexusCreations",
    url: "https://lexuscreations.herokuapp.com/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-02.jpg",
    hosted: "render",
    siteName: "CodeConnect",
    url: "https://codeconnect.onrender.com/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-03.jpg",
    hosted: "heroku",
    siteName: "CollaBoard-PC",
    url: "https://collaboardpc.herokuapp.com/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-04.jpg",
    hosted: "netlify",
    siteName: "LexusCreations",
    url: "https://lexuscreations.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-01.jpg",
    hosted: "github",
    siteName: "LexusCreations",
    url: "https://github.com/lexuscreations/lexuscreations",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-02.jpg",
    hosted: "githubPages",
    siteName: "LexusPrint",
    url: "https://lexuscreations.github.io/lexusprint/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-03.jpg",
    hosted: "netlify",
    siteName: "IndependentWomenCommunity",
    url: "https://independentwomencommunity.netlify.app/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-04.jpg",
    hosted: "githubPages",
    siteName: "TextCapital",
    url: "https://lexuscreations.github.io/textcapital/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-01.jpg",
    hosted: "githubPages",
    siteName: "LeapYearFinder",
    url: "https://lexuscreations.github.io/leapyearfinder/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-02.jpg",
    hosted: "githubPages",
    siteName: "DarkSite",
    url: "https://lexuscreations.github.io/darksite/",
  },
  {
    img: "https://tailwindui.com/img/ecommerce-images/product-page-05-related-product-03.jpg",
    hosted: "githubPages",
    siteName: "D2B-B2D-Converter",
    url: "https://lexuscreations.github.io/d2b-b2d-Converter/",
  },
];
